name: localfunc
hub:
  address: tcp://localhub:1883
  username: test
  password: hahaha
rules:
  - id: rule-e1iluuac1
    subscribe:
      topic: t
      qos: 1
    compute:
      function: sayhi
    publish:
      topic: t/hi
      qos: 1
  - id: rule-e1iluuac2
    subscribe:
      topic: t
      qos: 1
    compute:
      function: filter
    publish:
      topic: t/f
      qos: 1
functions:
  - id: func-ejvubz6bl
    name: 'filter'
    handler: 'select topic() as t, * where id < 10'
    entry: "hub.baidubce.com/openedge/openedge-function-runtime-sql"
  - id: func-nyeosbbch
    name: 'sayhi'
    handler: 'sayhi.handler'
    codedir: 'var/db/openedge/module/func-nyeosbbch'
    entry: "hub.baidubce.com/openedge/openedge-function-runtime-python27:0.1.1"
    env:
      USER_ID: acuiot
    instance:
      min: 0
      max: 10
      timeout: 1m
      cpu:
        cpus: 0.5
      memory:
        limit: 50m
logger:
  path: var/log/openedge/localfunc/localfunc.log
  console: true
  level: "debug"
