sudo: false

language: go

go:
  - 1.10.1
  
before_install:
  - go get github.com/tools/godep
  - godep restore
  - rm -rf $GOPATH/src/github.com/docker/docker/vendor/github.com/docker/go-connections
  - go test ./...

install: true
script:
  - echo "uint test end"