sudo: true

services:
  - dockerls

language: go

go:
  - 1.11.1
  
before_install:
  - go get github.com/tools/godep
  - godep restore
  - if [ ! -d $GOPATH/src/github.com/baidu/openedge ]; then mkdir -p $GOPATH/src/github.com/baidu/openedge; cp -r ./ $GOPATH/src/github.com/baidu/openedge; fi;
  - rm -rf $GOPATH/github.com/docker/docker/vendor
  - cd $GOPATH/src/github.com/baidu/openedge
  - go test ./...
  - chmod +x build.sh

install: true
script:
  - ./build.sh