sudo: false

language: go

go:
  - 1.10.1
  
before_install:
  - go get github.com/tools/godep
  - godep restore
  - if [ ! -d $GOPATH/src/github.com/baidu/openedge ]; mkdir -p $GOPATH/src/github.com/baidu/openedge; cp -r ./ $GOPATH/src/github.com/baidu/openedge; fi;
  - test_files=`find . -name *_test.go`
  - for f in $test_files; do test_dirs="$test_dirs `dirname $f` ";  done;
  - go test -cover $test_dirs;
  - chmod 777 build.sh

install: true
script:
  - ./build.sh