name: agent
remote:
  mqtt:
    clientid: 76ddb619ed3545dd9019ae9ac18ef036
    address: 'ssl://sandbox.mqtt.iot.bj.baidubce.com:8884'
    username: 50ae1649190f478d8ef23dc9aa0ffe8d/76ddb619ed3545dd9019ae9ac18ef036
    ca: cert/root.pem
    cert: cert/client.pem
    key: cert/client.key
  http:
    ca: cert/openapi.pem
    address: 'https://iot-edge.baidu-int.com'
logger:
  console: true
  level: debug
