mode: docker
cloud:
  clientid: 'fb753a1d2aea454f96083c6b2db03728'
  address: 'ssl://sandbox.mqtt.iot.bj.baidubce.com:8884'
  username: '6c2afc40cedd40678714e4adb694b488/fb753a1d2aea454f96083c6b2db03728'
  ca: 'conf/root.pem'
  cert: 'conf/client.pem'
  key: 'conf/client.key'
  openapi:
    address: 'https://iot-edge.baidu-int.com'
logger:
  path: var/log/openedge.log
  level: debug
  console: true
