version: V0
services:
  # - name: agent
  #   image: 'openedge-agent'
  #   datasets:
  #     - name: conf-agent
  #       target: etc/openedge
  #       readonly: true
  #     - name: cert-igeblfrt8
  #       target: cert
  #       readonly: true
  #   volumes:
  #     - volume: var/log/openedge/agent
  #       target: var/log/openedge
  - name: localhub
    image: 'openedge-hub'
    expose:
      - '1883:1883'
    datasets:
      - name: conf-localhub
        target: etc/openedge
        readonly: true
    volumes:
      - volume: var/db/openedge/volumes/localhub
        target: var/db/openedge
      - volume: var/log/openedge/localhub
        target: var/log/openedge
